#pacman/pacstrap config file to install archlinuxarm into rootfs
[options]
HoldPkg     = pacman glibc
Architecture = aarch64
Color
CheckSpace
ParallelDownloads = 5
DownloadUser = alpm
ILoveCandy
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Server = http://mirror.archlinuxarm.org/$arch/$repo

[extra]
Server = http://mirror.archlinuxarm.org/$arch/$repo

[community]
Server = http://mirror.archlinuxarm.org/$arch/$repo
